name: 'zava_fabric_dbt_medallion_demo'
version: '1.0.0'
config-version: 2

profile: 'zava_fabric_dbt_medallion_demo'

model-paths: ['models']

vars:
  # Change this to the Lakehouse item name that contains customers, orders, and products.
  bronze_lakehouse_name: 'ZavaLakehouse'

models:
  zava_fabric_dbt_medallion_demo:
    staging:
      +materialized: view
      +tags: ['silver']
    marts:
      +materialized: table
      +tags: ['gold']
