name: zava_medallion
version: 1.0
config-version: 2

model-paths: ["models"]

models:
  zava_medallion:
    silver:
      materialized: table
      tags: ["silver"]
    gold:
      materialized: table
      tags: ["gold"]
