version: 2

sources:
  - name: bronze
    database: "{{ var('bronze_lakehouse_name') }}"
    schema: dbo

    tables:
      - name: customers
        identifier: bronze_customers

      - name: orders
        identifier: bronze_orders

      - name: products
        identifier: bronze_products
